## code to prepare `example_usada_raw` dataset goes here
data.frame(Athlete = c("*Name Removed", "Richardson, Sha'Carri",
"*Name Removed", "*Name Removed", "Martin, Jeff", "Echeverri, Alejandra",
"*Name Removed", "*Name Removed", "Igbokwe, Obichukwu", "Hu, Yaozong",
"*Name Removed", "Hearn, Timothy", "Rollins, Brianna", "Penn, BJ",
"Zaleski dos Santos, Elizeu", "Ortiz, Robert", "*Name Removed",
"Anderson, Robert", "Oliver, Imani", "Wethington, Madeline",
"Munsell, Megan", "Bradley, Dominique", "Aira, Yoelkis", "Paulson, Ashley",
"Vande Velde, Christian", "Hay, Amy", "O'Keefe, Shannon", "*Name Removed",
"Scott, Bradley", "Harper-Nelson, Dawn", "Cachoeira Gomes da Silva, Priscila",
"Dixon, Reginald", "Armstrong, Lance", "Dahlkemper, Abigail",
"Koehly, Rebekah", "*Name Removed", "*Name Removed", "Bey, Kamal",
"Compton, Katherine", "*Name Removed", "Dollaway, CB", "Fagua Raquira, Ana Milena",
"Green, Roderick", "*Name Removed", "Thomas, Lorenzo", "*Name Removed",
"*Name Removed", "DiBuono, Matthew", "Rolo, Nelson", "Flood, Gregory",
"Estima, Braulio", "Spearmon, Jr., Wallace", "Frazier, Daniel",
"*Name Removed", "Gicquel, Barbara", "Dwyer, Conor", "Block, Mark",
"Danielson, Tom", "Jones, Jon", "*Name Removed", "Magomedov, Ruslan",
"*Name Removed", "Carrillo, Michel", "*Name Removed", "Zeng, Laura",
"Oliveira, Flavia", "*Name Removed", "Sorensen, Ira", "*Name Removed",
"Carnes, Andrew", "Walsh, Cole", "Abdelwahab, Hamdy", "Schmidt, Kyle",
"*Name Removed", "Andrew, Sidney", "Glasgow, Scott", "Fix, Daton",
"Magomedov, Ruslan", "Saccente, Nicholas", "*Name Removed", "Polk, Tori",
"Coleman, Ellis", "Klineman, Alexandra", "*Name Removed", "*Name Removed",
"*Name Removed", "Costa, Carlos", "*Name Removed", "de Tomas, Carls John",
"Tisinger-Ledkins, Janel", "Gaskins, Joshua", "Barnett, Josh",
"*Name Removed", "Bontorin, Rogerio", "Lopez, Enrique", "Schober, Zachary",
"Ngetich, Eliud", "Verrando-Higgins, Mary", "*Name Removed",
"Bracy, Addie", "McPherson, Inika", "*Name Removed", "Zabriskie, David",
"*Name Removed", "Diamond, Michael", "Anthony, David", "Robertson, Todd",
"Sullivan, George", "Berry, Gwen", "Lehr, Daniel", "*Name Removed",
"Palicka, Megan", "Kochem, Matt", "McPherson, Inika", "*Name Removed",
"Dunkum, Michael", "Lacoste, Jacob", "*Name Removed", "Wallhead, Jim",
"Mariita, Lilian", "Olivieri, Luis Felipe", "Boss, Logan", "Leinders, Geert",
"*Name Removed", "*Name Removed", "Howe, James", "*Name Removed",
"*Name Removed", "*Name Removed", "Ciolli, Kimberly", "Pessoa Nunes, Raphael",
"Hernandez, Roger", "Gonzalez Villa, Jorge", "McWhirter, Matt",
"Brown, Matthew", "*Name Removed", "Williams, Susanne", "Ostrander, Allison",
"Harris, Walt", "Hudson, Ryan", "Meeker, Richard", "Palmer, Liz",
"Evans-Smith, Ashlee", "Evans, Aja", "*Name Removed", "Nelson, James",
"Chipangama, Jordan", "Barnes, Benjamin", "*Name Removed", "Cardoso, José Henrique",
"*Name Removed", "Webster, Joshua", "*Name Removed", "Roberts, Lisa",
"Johnson, Gea", "Marquez, Marc", "Woolsey, Taff", "*Name Removed",
"*Name Removed", "Anyanwu, Azunna", "Carter, Chris", "*Name Removed",
"Willey, Quentin", "*Name Removed", "*Name Removed", "*Name Removed",
"*Name Removed", "Webb, Craig", "*Name Removed", "Santanna, Eduarda Neves",
"Le, Talina", "Ulloa, Camilo", "Barry, Michael", "Atkinson, Annie",
"Lochte, Ryan", "Mir, Francisco", "Cosby-Toruga, Jessica", "Costa, Paulo",
"da Costa Feliz, Igor Nascimento", "*Name Removed", "*Name Removed",
"Maynard, Nicole", "Beckwith-Ludlow, Molly", "Gough, Nicholas",
"Chavez, Bernabe", "Gochenour, Alexandria", "Celaya Lazama, Pedro",
"Cruse, J.C.", "*Name Removed", "*Name Removed", "*Name Removed",
"Park, Peter", "Williams, Nia", "Gingras, Michael", "*Name Removed",
"Montgomery, Kahmari", "*Name Removed", "Dana, Ryan", "Hisaka, Scott",
"Kyle, Cicely", "Ketema Asfaw, Atalelech", "McGillivray, Deanna",
"*Name Removed", "Alonso, Leynier", "*Name Removed", "Blanc, Obenson",
"*Name Removed", "Dolidze, Roman", "*Name Removed", "Moore, Darien",
"Chan, Charis", "Abreu, Ricardo", "Petrucci, Frank", "Shtyrkov, Ivan",
"Gastelum, Kelvin", "*Name Removed", "De Lima, Marcos Rogerio",
"Dreaver, Ted", "Schafer, Mallory", "Perry, Brett", "*Name Removed",
"*Name Removed", "Casey, Cortney", "Jarrett, Kaitlyn", "Hancock, Regina",
"Schiefer, John", "*Name Removed", "*Name Removed", "Oleksiejczuk, Michał",
"*Name Removed", "*Name Removed", "Alfred, Stephen", "Duarte, Kaynan",
"*Name Removed", "Corrigan, Lindsey", "*Name Removed", "Ferrari, Michele",
"Ostovich-Berdon, Rachael", "Ferraro,  Anthony", "Dickey, Duane",
"Matsushima, Angelique", "Shakirova, Liliya", "*Name Removed",
"Collier, Jake", "Bough, Gino", "Aivazian, Vahe", "Trafeh, Mohamed",
"Anderson, Kaley", "Montañez Barroso, Elias", "Forrest, Evan"
), Sport = c("Cycling", "Track and Field", "Track and Field",
"Bobsled and Skeleton", "Cycling", "Cycling", "Archery", "Roller Sports",
"Track and Field", "Mixed Martial Arts", "Cycling", "Weightlifting",
"Track and Field", "Mixed Martial Arts", "Mixed Martial Arts",
"Weightlifting", "Paralympic Track and Field, Paralympic Triathlon",
"Paralympic Judo", "Track and Field", "Ice Hockey", "Weightlifting",
"Wrestling", "Cycling", "Triathlon", "Cycling", "Weightlifting",
"Bowling", "Track and Field", "Mixed Martial Arts", "Track and Field",
"Mixed Martial Arts", "Track and Field", "Cycling", "Soccer",
"Weightlifting", "Karate", "Weightlifting", "Wrestling", "Cycling",
"Weightlifting", "Mixed Martial Arts", "Cycling", "Paralympic Track and Field, Paralympic Volleyball",
"Track and Field", "Rugby", "Swimming", "Judo", "Track and Field",
"Cycling", "Rowing", "Brazilian Jiu-Jitsu", "Track and Field",
"Cycling", "Track and Field", "Cycling", "Swimming", "Track and Field - Athlete Support Personnel",
"Cycling", "Mixed Martial Arts", "Track and Field", "Mixed Martial Arts",
"Cycling", "Cycling", "Track and Field", "Gymnastics", "Cycling",
"Fencing", "Cycling", "Rowing", "Track and Field", "Track and Field",
"Mixed Martial Arts", "Cycling", "Taekwondo", "Cycling", "Weightlifting",
"Wrestling", "Mixed Martial Arts", "Weightlifting", "Track and Field",
"Track and Field", "Wrestling", "Volleyball", "Cycling", "Weightlifting",
"Track and Field", "Mixed Martial Arts", "Cycling", "Mixed Martial Arts",
"Racquetball", "Weightlifting", "Mixed Martial Arts", "Wrestling",
"Mixed Martial Arts", "Cycling", "Weightlifting", "Track and Field",
"Cycling", "Gymnastics", "Track and Field", "Track and Field",
"Roller Sports", "Cycling", "Track and Field", "Cycling", "Cycling",
"Cycling", "Mixed Martial Arts", "Track and Field", "Weightlifting",
"Diving", "Weightlifting", "Rowing", "Track and Field", "Track and Field",
"Wrestling", "Weightlifting", "Track and Field", "Mixed Martial Arts",
"Track and Field", "Mixed Martial Arts", "Track and Field", "Cycling - Athlete Support Personnel",
"Swimming", "Judo", "Taekwondo", "Rowing", "Cycling", "Track and Field",
"Cycling", "Mixed Martial Arts", "Cycling", "Mixed Martial Arts",
"Cycling", "Paralympic Track and Field", "Bobsled and Skeleton",
"Weightlifting", "Track and Field", "Mixed Martial Arts", "Weightlifting",
"Cycling", "Track and Field", "Mixed Martial Arts", "Bobsled",
"Track and Field", "Weightlifting", "Track and Field", "Weightlifting",
"Gymnastics", "Brazilian Jiu-Jitsu", "Track and Field", "Cycling",
"Paralympic Triathlon", "Triathlon", "Cycling", "Weightlifting",
"Weightlifting", "Track and Field", "Mixed Martial Arts", "Mixed Martial Arts",
"Track and Field", "Track and Field", "Bobsled", "Cycling", "Bobsled and Skeleton and Track and Field",
"Paralympic Archery", "Track and Field", "Cycling", "Cycling",
"Mixed Martial Arts", "Taekwondo", "Cycling", "Cycling", "Judo",
"Swimming", "Mixed Martial Arts", "Track and Field", "Mixed Martial Arts",
"Brazilian Jiu-Jitsu", "Wrestling", "Basketball", "Weightlifting",
"Track and Field", "Triathlon", "Weightlifting", "Track and Field",
"Cycling - Athlete Support Personnel", "Bobsled and Skeleton",
"Track and Field", "Track and Field", "Shooting", "Paralympic Track and Field",
"Rugby", "Weightlifting - Athlete Support Personnel", "Team Handball",
"Track and Field", "Cycling", "Weightlifting", "Weightlifting",
"Weightlifting", "Track and Field", "Team Handball", "Track and Field",
"Cycling", "Cycling", "Wrestling", "Track and Field", "Mixed Martial Arts",
"Paralympic Cycling", "Track and Field", "Weightlifting", "Mixed Martial Arts",
"Rowing", "Mixed Martial Arts", "Mixed Martial Arts", "Boxing",
"Mixed Martial Arts", "Weightlifting", "Triathlon", "Speedskating",
"Weightlifting", "Bobsled and Skeleton", "Mixed Martial Arts",
"Weightlifting", "Weightlifting", "Cycling", "Swimming", "Softball",
"Mixed Martial Arts", "Track and Field", "Swimming", "Cycling",
"Brazilian Jiu-Jitsu", "Paralympic Powerlifting", "Taekwondo",
"Paralympic Alpine Skiing", "Cycling - Athlete Support Personnel",
"Mixed Martial Arts", "Paralympic Judo", "Cycling", "Weightlifting",
"Mixed Martial Arts", "Paralympic Track and Field", "Mixed Martial Arts",
"Karate", "Cycling", "Track and Field", "Weightlifting", "Cycling",
"Weightlifting"), Substance.Reason = c("Non-Analytical: Use and Possession (EPO)",
"Cannabinoids", "Non-Analytical: Refusal to Submit to Sample Collection",
"Elevated T/E", "Androgenic Anabolic Steroid", "Chlorothiazide; Non-Analytical: Use (IV)",
"Non-Analytical: Refusal to Submit to Sample Collection", "Non-Analytical: 3 Whereabouts Failures",
"Dehydrochloromethyltestosterone (DHCMT)", "Androsta-3,5-diene-7,17-dione",
"Cannabinoids", "19-norandrosterone (19-NA); Trenbolone; Clomiphene; GW1516; Non-Analytical: Use (IV and Blood Transfusion)",
"Non-Analytical: 3 Whereabouts Failures", "Non-Analytical: Use (IV)",
"Ostarine", "1,4‐dimethylpentylamine", "Oxilofrine", "Non-Analytical: Use (Vilanterol)",
"Ostarine", "Spironolactone", "GW1516", "Methylhexaneamine",
"Phentermine", "Ostarine", "Non-Analytical: Use (EPO, hGH, Testosterone, Cortisone)",
"Ostarine", "Clomiphene", "Methylhexanamine", "Cocaine", "Hydrochlorothiazide",
"Hydrochlorothiazide", "Non-Analytical: 3 Whereabouts Failures",
"Non-Analytical: Use, Possession, Trafficking, Administration and Complicity",
"Spironolactone", "Testosterone", "Pseudoephedrine", "Methylhexaneamine",
"Non-Analytical: 3 Whereabouts Failures", "Androgenic Anabolic Steroid",
"Stanozolol Metabolites", "Anastrozole; GHRP-2; GHRP-6; Clomiphene",
"Androgenic Anabolic Steroid", "Ostarine", "Finasteride & 6-oxo-androstenedione and its metabolite 6a-hydroxyandrostenehione",
"GW1516", "Non-Analytical: Refusal to Submit to Sample Collection",
"Non-Analytical: Missed Tests", "Androgenic Anabolic Steroid",
"Benzoylecgonine", "Glycerol", "Methylhexaneamine", "Methylprednisolone",
"Androgenic Anabolic Steroid, Clomiphene", "Cannabinoids", "Methyltestosterone",
"Androgenic Anabolic Steroid", "Non-Anatlyical: Administration and Trafficking",
"Androgenic Anabolic Steroid", "Clomiphene, Letrozole", "Amphetamine & Methamphetamine",
"Methyltestosterone; Stanozolol", "Methylhexaneamine", "Erythropoietin (EPO); 19‐norandrosterone (19‐NA); Androgenic-anabolic steroids (AAS); Clostebol, Testosterone",
"Non-Analytical Positive", "Acetazolamide", "Oxilofrine", "Pseudoephdrine",
"Androgenic Anabolic Steroid", "Non-Analytical: Missed Tests",
"Non-Analytical: Possession, Use and Possession (EPO)", "Cannabinoids",
"Methenolone; Non-Analytical: Tampering", "Non-Analytical: Use and Possession (EPO)",
"Methylhexaneamine", "5-methylhexan-2-amine", "Non-Analytical: Complicity",
"Ostarine", "Ostarine", "Non-Analytical: Possession and Use/Attempted Use; Non-Analytical: 3 Whereabouts Failures",
"Methandienone (Dianabol)", "Non-Analytical: Possession (Peptides)",
"Dehydroepiandrosterone (DHEA)", "Androgenic Anabolic Steroid",
"Androgenic Anabolic Steroid", "Cannabinoids", "Ephedrine", "Non-Analytical: Possession and Administration",
"Non-Analytical: Purchase, Possession and Use (EPO)", "Furosemide",
"Octopamine", "Androgenic Anabolic Steroids", "Ostarine", "Triamcinolone Acetonide",
"Hydrochlorothiazide (HCTZ)", "Erythropoietin (EPO)", "Amphetamine; Methylphenidate; GW1516",
"Nandrolone", "Metabolites of Methyltestosterone", "Triamcinolone Acetonide",
"Non-Analytical: Use (Intravenous Infusion)", "Benzoylecgonine",
"Androgenic Anabolic Steroid, 19-Norandrosterone (19-NA), and Human Chorionic Gonadotrophin (hCG)",
"Non-Analytical: Use (EPO, hGH, Testosterone)", "Non-Analytical",
"Non-Analytical: Refusal to Submit to Sample Collection", "Erythropoietin (EPO)",
"Erythropoietin (EPO)", "Clomiphene and its metabolite", "Non-Analytical: Use (Vilanterol)",
"Androstenedione, Ostarine", "Cannabinoids", "Ostarine and RAD140",
"Non-Analytical: 3 Whereabouts Failures", "Furosemide", "Non-Analytical: Use",
"Non-Analytical: Use and Possession (Peptides)", "Clomiphene; 19-norandrosterone (19-NA)",
"Cannabinoids", "Ostarine", "Androgenic Anabolic Steroid", "Methyltestosterone",
"Canrenone", "Non-Analytical: Possession, Trafficking, and Administration",
"Methylphenidate", "Methylphenidate metabolite Ritalinic Acid",
"Cannabinoids", "Formoterol and Budesonide", "Phentermine", "Non-Analytical",
"Androgenic Anabolic Steroid and Propylhexadrine", "Hydrochlorothiazide (HCTZ)",
"Non-Analytical: Refusal to Submit to Sample Collection", "Stanozolol; Drostanolone",
"Androgenic Anabolic Steroid", "Hydrochlorothiazide & Chlorothiazide",
"Methandienone", "Ostarine", "Canrenone", "LGD-4033", "Stanozolol Metabolites",
"19-norandrosterone (19-NA) and 19-noretiocholanolone", "Methandienone metabolite",
"Dehydroepiandrosterone (DHEA)", "Non-Analytical: Refusal to Submit to Sample Collection",
"Modafinil", "Dehydrochloromethyltestosterone (DHCMT)", "Meldonium",
"GW1516", "Triamcinolone Acetonide", "19-norandrosterone (19-NA); 2a-methyl-5a-androstan-3a-ol-17-one; Epitrenbolone; Methasterone; Testosterone",
"Ephedrine", "Methylhexaneamine & Phenpromethamine", "Hydrochlorothiazide (HCTZ)",
"Vilanterol", "Modafinil", "Cannabinoids", "Non-Analytical: Possession (Exemestane)",
"Probenecid", "Meldonium", "Furosemide", "Ostarine", "19-norandrosterone (19-NA)",
"Boldenone", "Cannabinoids", "Non-Analytical: Manipulation of Forms & Stanozolol",
"Hydrochlorothiazide, Chlorothiazide, Triamterene and Labetalol",
"Hydrochlorothiazide (HCTZ)", "Non-Analytical: Refusal to Submit to Sample Collection",
"Cannabinoids", "LGD-4033", "Higenamine", "Androgenic Anabolic Steroid and Methylphenidate",
"Non-Analytical: Use (EPO, hGH, Testosterone)", "Hydrochlorothiazide, Chlorothiazide, Triamterene, 4-hydroxytriamterene",
"Non-Analytical: Use (IV)", "Dehydrochloromethyltestosterone (DHCMT)",
"Hydrochlorothiazide & Chlorothiazide", "Non-Analytical: Intravenous Infusion",
"Testosterone", "Phentermine", "Salmeterol", "Methenolone; LGD‐4033; GW1516",
"Clomiphene", "Erythropoietin (EPO)", "Non-Analytical: Tampering, Complicity",
"Ostarine", "Non-Analytical", "Dimethylbutylamine (DMBA)", "Non-Analytical: Refusal to Submit to Sample Collection",
"Non-Analytical", "Hydrochlorothiazide and Chlorothiazide", "Androgenic Anabolic Steroid",
"19-Norandrosterone (19-NA), 19-noretiocholanolone, and Drostanolone and its metabolites",
"Non-Analytical: Possession, Trafficking, and Administration",
"Cannabinoids", "Cannabinoids", "Non-Analytical: Failure to Appear to Sample Collection",
"Androgenic Anabolic Steroid", "Non-Analytical: Possession and Use/Attempted Use",
"Androgenic Anabolic Steroid", "Ephedrine", "Trenbolone, Epitrenbolone",
"Androstendione", "Phentermine", "Tamoxifen and its metabolite, Anastrozole, Letrozole, Human Chorionic Gonadotrophin (HCG), and Clomiphene",
"Ostarine", "Hydrochlorothiazide", "Clomiphene; Dehydrochloromethyltestosterone (DHCMT)",
"Hydrochlorothiazide", "Methandienone", "Epitrenbolone", "Androgenic Anabolic Steroid & 19-norandrosterone (19-NA)",
"Glycerol", "Boldenone", "Cannabinoids", "Cannabinoids", "Anastrozole; Hydrochlorothiazide",
"Androgenic Anabolic Steroid", "Higenamine", "Methylphenidate and its metabolite",
"Methylphenidate metabolite Ritalinic Acid", "Finasteride", "BPC-157",
"Higenamine", "Stanozolol", "Clomiphene and its metabolite",
"Meldonium", "LGD-4033", "Clomiphene", "Amphetamine", "Non-Analytical: Refusal to Submit to Sample Collection",
"Non-Analytical: Refusal to Submit to Sample Collection", "Ostarine",
"Boldenone", "Non-Analytical: Refusal to Submit to Sample Collection",
"Non-Analytical: Missed Tests", "Non-Analytical", "Ostarine; GW1516",
"Cannabinoids", "Non-Analytical: Refusal to Submit to Sample Collection, Possession and Use (EPO)",
"Cannabinoids", "Meldonium", "Benzoylecgonine", "Higenamine",
"Non-Analytical: 3 Whereabouts Failures", "Testosterone;\tNandrolone; \tDehydroepiandrosterone (DHEA); \tSomatropin (hGH); Ipamorelin; \tGHRP-6; CJC-1295;  IGF-1; Human chorionic gonadotropin (hCG); Anastrozole",
"Non-Analytical: Use and Possession (EPO), and Evading Sample Collection",
"Di‐hydroxy‐LGD‐4033", "Non-Analytical: Refusal to Submit to Sample Collection",
"Boldenone; Drostanolone; Methandienone; Nandrolone; Testosterone"
), Sanction.Terms = c("2-Year Suspension - Loss of Results",
"1-Month Suspension; Loss of Results", "2-Year Suspension - Loss of Results",
"2-Year Suspension - Loss of Results", "2-Year Suspension; Loss of Results",
"12-Month Suspension; Loss of Results", "2-Year Suspension - Loss of Results",
"1-Year Suspension - Loss of Results", "30-Month Suspension; Loss of Results",
"10-Month Suspension", "3-Month Suspension with 3-Month Deferral - Loss of Results",
"3-Year Suspension; Loss of Results", "1-Year Suspension - Loss of Results",
"6-Month Suspension", "1-Year Suspension", "16-Month Suspension - Loss of Results",
"6-Month Suspension - Loss of Results", "3-Month Suspension - Loss of Results",
"1-Year Suspension - Loss of Results", "Public Warning", "4-Year Suspension; Loss of Results",
"8-Month Suspension - Loss of Results", "2-Year Suspension - Loss of Results",
"6-Month Suspension - Loss of Results", "6-Month Suspension - Loss of Results",
"2-Year Suspension; Loss of Results; Sanction Reduced; Unretired - Eligible to compete starting 07/25/2020",
"Public Warning", "6-Month Suspension - Loss of Results", "2-Year Suspension; Sanction tolled due to retirement",
"3-Month Suspension - Loss of Results", "4-Month Suspension",
"1-Year Suspension - Loss of Results", "Lifetime Suspension - Loss of Results",
"Public Warning", "20-Month Suspension; Loss of Results", "1-Month Suspension - Loss of Results",
"6-Month Suspension - Loss of Results", "1-Year Suspension; Loss of Results",
"4-Year Suspension; Loss of Results", "2-Year Suspension - Loss of Results",
"2-Year Suspension", "4-Year Suspension - Loss of Results", "9-Month Suspension - Loss of Results",
"8-Year Suspension with 4-Year Reduction - Loss of Results",
"4-Year Suspension; Loss of Results", "4-Year Suspension - Loss of Results",
"2-Year Suspension", "4-Year Suspension - Loss of Results", "1-Year Suspension - Loss of Results",
"Public Warning - Loss of Results", "2-Year Suspension - Loss of Results",
"3-Month Suspension - Loss of Results", "1-Year Suspension - Loss of Results",
"3-Month Suspension with 3-Month Deferral - Loss of Results",
"1-Year Suspension; Loss of Results", "20-Month Suspension; Loss of Results; Sanction tolled due to retirement",
"10 Year Suspension", "4-Year Suspension - Loss of Results; Second Violation",
"1-Year Suspension", "2-Year Suspension - Loss of Results", "Lifetime Suspension",
"8 Month Suspension - Loss of Results", "4-Year Suspension; Loss of Results",
"2-Year Suspension - Loss of Results", "6-Month Suspension; Loss of Results",
"18-Month Suspension - Loss of Results", "3-Month Suspension - Loss of Results",
"2-Year Suspension; Loss of Results", "2-Year Suspension", "2-Year Suspension - Loss of Results",
"6-Month Suspension with 3-Month Deferral; Loss of Results",
"2-Year Suspension", "2-Year Suspension - Loss of Results", "6-Month Suspension - Loss of Results",
"12-Month Suspension; Loss of Results", "4-Year Suspension",
"1-Year Suspension; Loss of Results", "2-Year Suspension", "8-Year Suspension; Loss of Results; Sanction tolled due to retirement",
"2-Year Suspension - Loss of Results", "2-Year Suspension - Loss of Results",
"24-Month Suspension; Loss of Results", "13-Month Suspension - Loss of Results",
"2-Year Suspension - Loss of Results \nSuspension Extended 103 Days",
"3-Month Suspension with 3-Month Deferral - Loss of Results",
"Public Warning - Loss of Results", "6-Month Suspension", "2-Year Suspension - Loss of Results",
"1-Year Suspension", "16-Month Suspension; Loss of Results",
"2-Year Suspension - Loss of Results", "Public Warning", "Public Warning - Loss of Results",
"3-Month Suspension", "4-Year Suspension - Loss of Results",
"4-Year Suspension; Loss of Results", "1-Year Suspension; Loss of Results",
"1-Year Suspension - Loss of Results", "Public Warning - Loss of Results",
"Public Warning", "21-Month Suspension - Loss of Results", "2-Year Suspension - Loss of Results",
"6-Month Suspension - Loss of Results", "2-Year Suspension - Loss of Results",
"2-Year Suspension - Loss of Results", "2-Year Suspension - Loss of Results",
"2-Year Suspension with 9 Month Reduction - Loss of Results",
"1-Year Suspension; Second Violation", "3-Month Suspension - Loss of Results",
"4-Year Suspension with 3-Month Reduction - Loss of Results",
"1-Year Suspension - Loss of Results", "3-Year Suspension - Loss of Results; Sanction tolled due to retirement",
"1-Year Suspension - Loss of Results", "16-Month Suspension; Loss of Results",
"2-Year Suspension - Loss of Results", "4-Year Suspension - Loss of Results; Sanction tolled due to retirement",
"3-Year Suspension; Loss of Results", "Public Warning - Loss of Results",
"9-Month Suspension", "8-Year Suspension - Loss of Results",
"2-Year Suspension", "Public Warning", "Lifetime Suspension",
"2-Year Suspension - Loss of Results", "2-Year Suspension - Loss of Results",
"6-Month Suspension with 3-Month Deferral - Loss of Results",
"Public Warning - Loss of Results", "2-Year Suspension - Loss of Results",
"2-Year Suspension - Loss of Results; Second Violation", "2-Year Suspension - Loss of Results",
"1-Year Suspension", "2-Year Suspension - Loss of Results", "2-Year Suspension",
"4-Year Suspension; Loss of Results", "1-Year Suspension - Loss of Results; Second Violation",
"2-Year Suspension - Loss of Results", "4-Year Suspension; Loss of Results",
"4-Month Suspension; Loss of Results", "4-Month Suspension",
"4-Year Suspension - Loss of Results", "2-Year Suspension - Loss of Results",
"4-Year Suspension with 6 Month Reduction - Loss of Results",
"14-Month Suspension", "2-Year Suspension; Loss of Results",
"2-Year Suspension - Loss of Results", "4-Year Suspension; Loss of Results",
"4-Year Suspension - Loss of Results", "4-Year Suspension - Loss of Results",
"Public Warning - Loss of Results", "3-Year Suspension; Loss of Results",
"Public Warning - Loss of Results", "2-Year Suspension - Loss of Results",
"No Fault or Negligence", "Public Warning - Loss of Results",
"21-Month Suspension - Loss of Results", "3-Month Suspension; Loss of Results",
"2-Year Suspension; Loss of Results", "No Fault or Negligence",
"No Fault or Negligence", "1-Year Suspension", "9-Month Suspension - Loss of Results",
"2-Year Suspension - Loss of Results", "3-Year Suspension; Loss of Results",
"3-Month Suspension with 3-Month Deferral - Loss of Results",
"2-Year Suspension - Loss of Results", "Public Warning - Loss of Results",
"No Fault or Negligence", "4-Year Suspension - Loss of Results",
"1-Year Suspension - Loss of Results", "1-Year Suspension", "18-Month Suspension; Loss of Results",
"4-Year Suspension - Loss of Results", "6-Month Suspension - Loss of Results",
"3-Month Suspension - Loss of Results", "14-Month Suspension",
"2-Year Suspension", "4 Month Suspension - Loss of Results",
"6-Month Suspension", "3-Year Suspension; Loss of Results", "2-Year Suspension - Loss of Results",
"Public Warning - Loss of Results", "4-Year Suspension; Loss of Results",
"Public Warning", "4-Year Suspension - Loss of Results", "4-Year Suspension",
"4-Year Suspension; Loss of Results", "Lifetime Suspension",
"16-Month Suspension - Loss of Results", "1-Year Suspension - Loss of Results",
"2-Year Suspension - Loss of Results", "6-Month Suspension - Loss of Results",
"21-Month Suspension - Loss of Results", "4-Year Suspension - Loss of Results",
"Lifetime Suspension with Reduction  to 12 Years - Loss of Results; Sanction tolled due to retirement",
"2-Year Suspension - Loss of Results", "1-Month Suspension; Loss of Results",
"Public Warning", "21-Month Suspension - Loss of Results", "4-Year Suspension; Loss of Results",
"2-Year Suspension - Loss of Results", "2-Year Suspension - Loss of Results",
"2-Year Suspension - Loss of Results", "2-Year Suspension - Loss of Results",
"4-Year Suspension; Loss of Results", "2-Year Suspension - Loss of Results",
"2-Year Suspension - Loss of Results", "1-Year Suspension - Loss of Results",
"1-Year Suspension", "No Fault or Negligence", "4-Year Suspension - Loss of Results",
"4-Year Suspension - Loss of Results", "4-Year Suspension: Sanction is tolled until athlete returns from retirement. Second Violation.",
"Public Warning - Loss of Results", "2-Year Suspension", "6-Month Suspension with 3-Month Deferral",
"3-Month Suspension with 3-Month Deferral - Loss of Results",
"6-Month Suspension", "39-Month Suspension; Loss of Results",
"10-Month Suspension", "9-Month Suspension - Loss of Results",
"1-Year Suspension - Loss of Results", "1-Year Suspension - Loss of Results",
"4-Month Suspension", "1-Year Suspension - Loss of Results",
"4-Year Suspension; Loss of Results", "6-Month Suspension - Loss of Results",
"No Fault or Negligence - Loss of Results", "No Fault or Negligence",
"1-Year Suspension", "2-Year Suspension - Loss of Results", "2-Year Suspension",
"Lifetime Suspension; Third Violation", "1-Year Suspension",
"2-Year Suspension - Loss of Results", "2-Year Suspension; Loss of Results",
"2-Year Suspension - Loss of Results", "Lifetime Suspension",
"1-Year Suspension", "6-Month Suspension with 3-Month Deferral - Loss of Results",
"Lifetime Suspension - Loss of Results", "6-Month Suspension with 3-Month Deferral - Loss of Results",
"2-Year Suspension", "2-Year Suspension - Loss of Results", "10-Month Suspension",
"1-Year Suspension - Loss of Results", "4-Year Suspension; Loss of Results",
"4-Year Suspension - Loss of Results", "4-Year Suspension; Loss of Results",
"4-Year Suspension; Loss of Results", "3-Year Suspension; Loss of Results"
), Sanction.Announced = c("", "07/02/2021", "", "", "10/01/2020",
"02/14/2023", "", "", "04/08/2021", "06/14/2019", "", "09/06/2022",
"04/20/2017", "06/27/2016", "09/22/2022", "08/27/2018", "", "08/04/2016",
"05/09/2017", "12/06/2021", "12/22/2020", "09/06/2013", "09/05/2013",
"03/31/2016", "10/10/2012", "Original: 10/31/2017; Updated: 12/16/2019",
"03/14/2014", "", "10/16/2018", "02/07/2017", "12/18/2019", "06/06/2014",
"08/24/2012", "05/04/2018", "04/28/2021", "", "", "10/30/2020",
"08/11/2021", "", "08/26/2019", "09/01/2016", "03/14/2017", "",
"03/04/2021", "", "", "10/07/2011", "12/11/2015", "08/20/2013",
"11/25/2014", "09/19/2014", "08/15/2018", "", "08/14/2020", "10/11/2019",
"03/17/2011", "10/06/2016", "11/07/2016", "", "04/01/2019", "",
"01/18/2019", "", "12/19/2018", "Original: 04/13/2010; Updated 12/10/2010",
"", "02/12/2019", "", "04/18/2014", "06/01/2020", "02/03/2023",
"06/02/2015", "", "12/05/2022", "12/20/2019", "09/08/2020", "02/15/2018",
"04/16/2020", "", "12/15/2017", "08/31/2022", "12/20/2013", "",
"", "", "04/26/2019", "", "02/05/2018", "05/02/2019", "08/22/2018",
"03/23/2018", "", "09/29/2021", "11/12/2018", "04/19/2023", "Original: 09/03/21; Updated: 01/25/22",
"08/15/2016", "", "06/26/2023", "12/19/2014", "", "10/10/2012",
"", "11/18/2011", "07/25/2012", "03/30/2012", "06/20/2017", "06/13/2016",
"05/02/2016", "", "04/06/2018", "04/13/2012", "04/14/2023", "",
"11/07/2016", "09/29/2021", "", "02/06/2018", "12/28/2015", "01/25/2017",
"12/06/2017", "01/22/2015", "", "", "07/12/2016", "", "", "",
"08/22/2016", "11/23/2020", "10/06/2011", "09/11/2020", "09/30/2021",
"08/03/2012", "", "12/16/2020", "08/25/2023", "04/22/2019", "12/15/2016",
"11/26/2013", "08/03/2016", "05/16/2022", "11/18/2022", "", "07/01/2021",
"05/15/2018", "06/30/2017", "", "03/08/2023", "", "07/15/2011",
"", "11/10/2017", "07/07/2017", "04/28/2023", "07/22/2020", "",
"", "03/02/2018", "08/11/2017", "", "04/18/2023", "", "", "",
"", "01/26/2018", "", "01/15/2021", "07/08/2019", "10/26/2016",
"10/10/2012", "02/28/2014", "07/23/2018", "04/21/2017", "05/10/2010",
"04/26/2019", "03/08/2023", "", "", "09/04/2019", "05/01/2017",
"04/02/2018", "02/04/2022", "12/17/2019", "Original: 04/22/2014;Updated: 10/24/2018",
"07/20/2017", "", "", "", "06/08/2017", "06/13/2016", "05/11/2017",
"", "06/03/2021", "", "10/09/2014", "01/05/2021", "12/30/2015",
"03/12/2015", "04/02/2015", "", "06/30/2020", "", "05/15/2014",
"", "08/23/2019", "", "05/04/2017", "01/09/2017", "05/05/2017",
"08/20/2013", "07/09/2019", "05/11/2017", "", "04/23/2018", "01/06/2020",
"07/30/2019", "02/26/2014", "", "", "09/14/2023", "03/23/2018",
"08/11/2021", "09/06/2017", "", "", "06/12/2018", "", "", "02/05/2008",
"02/07/2020", "", "05/09/2023", "", "07/10/2012", "06/18/2020",
"08/08/2018", "09/10/2010", "01/06/2017", "08/30/2021", "", "02/19/2019",
"07/25/2016", "04/15/2021", "Original: 12/18/2014; Updated: 08/25/2015",
"11/20/2019", "01/10/2023", "11/30/2023"))
usethis::use_data(example_usada_raw, overwrite = TRUE)
