## code to prepare `s1_substances` dataset goes here
s1_substances <-
  c(
    # 3α-hydroxy-5α-androst-1-en-17-one ----
    # https://ufc.usada.org/ovince-saint-preux-accepts-second-doping-sanction/
    # https://www.wada-ama.org/en/prohibited-list?page=0&q=Androstenedione&all=1#search-anchor
    "3α-hydroxy-5α-androst-1-en-17-one",
    "androgenic anabolic steroid",
    "androgenic anabolic steroids",
    "anabolic agent",
    "anabolic agents",
    "anabolic steroid",
    "anabolic steroids",
    "androstenedione",
    "metabolites of androstenedione",
    "1-androstenediol (5α-androst-1-ene-3β,17β-diol)",
    "1-androstenedione",
    "1-androstenedione (5α-androst-1-ene-3,17-dione)",
    "1-androsterone (3α-hydroxy-5α-androst-1-ene-17-one)",
    "androstendione",
    "androstenedione",
    "1-testosterone (17β-hydroxy-5α-androst-1-en-3-one)",
    "bolasterone",
    "boldione",
    "calusterone",
    "clostebol",
    "danazol ([1,2]oxazolo[4',5':2,3]pregna-4-en-20-yn-17α-ol)",
    "dehydrochlormethyltestosterone (4-chloro-17β-hydroxy17α-methylandrosta-1,4-dien-3-one)",
    "desoxymethyltestosterone (17α-methyl-5α-androst2-en-17β-ol and 17α-methyl-5α-androst-3-en-17β-ol)",
    "dhcmt",
    "di‐hydroxy‐lgd‐4033",
    "drostanolone",
    "elevated t/e",
    # elevated t/e ----
    # If an athlete’s testosterone/epitestosterone (T/E) ratio is greater than the
    # 6:1 limit, a further study be conducted to determine whether the individual
    # has a naturally elevated T/E ratio
    "ethylestrenol (19-norpregna-4-en-17α-ol)",
    "epitrenbolone",
    "epitrenbolone",
    "fluoxymesterone",
    "formebolone",
    "furazabol (17α-methyl [1,2,5]oxadiazolo[3',4':2,3]-5αandrostan-17β-ol)",
    "gestrinone",
    "hydroxyandrostendione",
    "lgd4033",
    "lgd‐4033",
    # lgd‐4033 ----
    # https://www.usada.org/spirit-of-sport/education/5-things-to-know-about-lgd-4033/
    # LGD-4033 is a selective androgen receptor modulator (SARM)
    "methandienone",
    "methandienone (dianabol)",
    "methandienone metabolite",
    "mestanolone",
    "mesterolone",
    "metandienone",
    "methasterone",
    # methasterone ----
    # https://en.wikipedia.org/wiki/Methasterone
    # ' orally active anabolic–androgenic steroid '
    "metandienone (17β-hydroxy-17α-methylandrosta-1,4-dien3-one)",
    "metenolone",
    "methenolone",
    "methandriol",
    "methasterone (17β-hydroxy-2α,17α-dimethyl-5αandrostan-3-one)",
    "methyldienolone (17β-hydroxy-17α-methylestra-4,9-dien3-one)",
    "methyl-1-testosterone (17β-hydroxy-17α-methyl-5αandrost-1-en-3-one)",
    "methylnortestosterone (17β-hydroxy-17α-methylestr-4-en3-one)",
    "methyltestosterone",
    "metribolone (methyltrienolone, 17β-hydroxy-17αmethylestra-4,9,11-trien-3-one)",
    "mibolerone",
    "nandrolone",
    "norbolethone",
    "norandrosterone",
    "noretiocholanolone",
    "norboletone",
    "norclostebol",
    "norethandrolone",
    "oxabolone",
    "oxandrolone",
    "oxymesterone",
    "oxymetholone",
    "prostanozol",
    "17β-tetrahydropyran-2-yl-oxy",
    "hpyrazolo[3,4:2,3]-5α-androstane",
    "quinbolone",
    "stanozolol",
    "stenbolone",
    "tetrahydrogestrinone (17-hydroxy-18a-homo-19-nor-17αpregna-4,9,11-trien-3-one)",
    "trenbolone (17β-hydroxyestr-4,9,11-trien-3-one)",
    "4-androstenediol (androst-4-ene-3β,17β-diol)",
    "4-hydroxytestosterone (4,17β-dihydroxyandrost-4-en-3-one)",
    "5-androstenedione (androst-5-ene-3,17-dione)",
    "7α-hydroxy-dhea",
    "7β-hydroxy-dhea",
    "7-keto-dhea",
    "19-norandrostenediol (estr-4-ene-3,17-diol)",
    "19-norandrostenedione (estr-4-ene-3,17-dione)",
    "androstanolone (5α-dihydrotestosterone, 17β-hydroxy-5αandrostan-3-one)",
    "androstenediol (androst-5-ene-3β,17β-diol)",
    "androstenedione (androst-4-ene-3,17-dione)",
    "boldenone",
    "boldione (androsta-1,4-diene-3,17-dione)",
    "epiandrosterone (3β-hydroxy-5α-androstan-17-one)",
    "epi-dihydrotestosterone (17β-hydroxy-5β-androstan-3-one)",
    "epitestosterone",
    "nandrolone (19-nortestosterone)",
    "prasterone (dehydroepiandrosterone, dhea,",
    "3β-hydroxyandrost-5-en-17-one)",
    "testosterone",
    "clenbuterol",
    "selective androgen receptor modulators (sarms)",
    "andarine",
    "lgd-4033",
    "enobosarm",
    "ostarine",
    "rad140",
    "tibolone",
    "trenbolone",
    "zeranol",
    "zilpaterol",
    "dehydroepiandrosterone",
    "dhea",
    "stanozolol",
    "dehydrochloromethyltestosterone",
    "drostanolone",
    "dromostanolone",
    "19-norandrosterone",
    "19-na",
    "clenbuterol",
    "stanozolol",
    "boldenone",
    "lgd-4033",
    "ostarine")
usethis::use_data(s1_substances, overwrite = TRUE)
