## code to prepare `s2_substances` dataset goes here
s2_substances <-
  c("alexamorelin",
    "anamorelin",
    "aod-9604",
    "argon",
    "asialo epo",
    "buserelin",
    "carbamylated epo (cepo)",
    "chorionic gonadotrophin (cg)",
    "cjc-1293",
    "cjc-1295",
    "cnto-530",
    "cobalt",
    "corticorelin",
    "corticotrophins",
    "daprodustat (gsk1278863)",
    "darbepoetins (depo)",
    "deslorelin",
    "epo based constructs",
    "epo-fc, methoxy polyethylene glycol-epoetin beta (cera)",
    "epo-mimetic agents and their constructs",
    "erythropoietin-receptor agonists",
    "epo",
    "(epo)",
    "erythropoietin",
    "erythropoietins",
    "erythropoietin (epo)",
    "erythropoietins (epo)",
    "examorelin (hexarelin)",
    "fibroblast growth factors (fgfs)",
    "gata inhibitors",
    "gh-releasing peptides (ghrps)",
    "ghrp-1",
    "ghrp-2 (pralmorelin)",
    "ghrp-2",
    "ghrp-3",
    "ghrp-4",
    "ghrp-5",
    "ghrp-6",
    "gonadorelin",
    "goserelin",
    "growth factor modulators",
    "growth factors",
    "growth factors",
    "(hgh)",
    "human growth hormone",
    "human growth hormone (hgh)",
    "(gh)",
    "growth hormone",
    "growth hormone (gh)",
    "growth hormone-releasing",
    "growth hormone releasing",
    "growth hormone fragments",
    "growth hormone releasing hormone (ghrh)",
    "growth hormone secretagogues (ghs)",
    "hepatocyte growth factor (hgf)",
    "hgh 176-191",
    "insulin-like growth factor-1 (igf-1)",
    "ipamorelin",
    "ibutamoren",
    "k-11706",
    "lenomorelin (ghrelin)",
    "leuprorelin",
    "luspatercept",
    "luteinizing hormone (lh)",
    "macimorelin",
    "mechano growth factors (mgfs)",
    "mimetics",
    "molidustat (bay 85-3934)",
    "nafarelin",
    "peginesatide",
    "peptide hormones",
    "peptide hormones",
    "platelet-derived growth factor (pdgf)",
    "roxadustat (fg-4592)",
    "sermorelin",
    "sotatercept",
    "tabimorelin",
    "tb-500",
    "tesamorelin",
    "tgf-beta (tgf-β) inhibitors",
    "thymosin-β4",
    "triptorelin",
    "vadadustat (akb-6548)",
    "vascular-endothelial growth factor (vegf)",
    "xenon")
usethis::use_data(s2_substances, overwrite = TRUE)
