## code to prepare `s4_substances` dataset goes here
s4_substances <-
  c("2-(2-methyl-4-((4-methyl-2-(4-(trifluoromethyl)phenyl)thiazol-5-yl)methylthio)phenoxy)",
    "2-androstenol (5α-androst-2-en-17-ol)",
    "2-androstenone (5α-androst-2-en-17-one)",
    "3-androstenol (5α-androst-3-en-17-ol)",
    "3-androstenone (5α-androst-3-en-17-one)",
    "4-androstene-3,6,17 trione (6-oxo)",
    "ace-031",
    "acetic acid",
    "activators of the amp-activated protein kinase (ampk)",
    "activin a-neutralizing antibodies",
    "activin receptor iib competitors",
    "agents preventing activin receptor iib activation",
    "agents reducing or ablating myostatin expression",
    "aicar",
    "aminoglutethimide",
    "anastrozole",
    "androsta-1,4,6-triene-3,17-dione (androstatrienedione)",
    "androsta-3,5-diene-7,17-dione (arimistane)",
    "androsta-3,5-diene-7,17-dione",
    "androsta",
    "anti-activin receptor iib antibodies",
    "anti-estrogenic substances",
    "aromatase inhibitors",
    "bimagrumab",
    "clomifene",
    "clomiphene",
    "cyclofenil",
    "decoy activin receptors",
    "domagrozumab",
    "exemestane",
    "follistatin",
    "formestane",
    "fulvestrant",
    "gw1516",
    "gw501516",
    "insulin",
    "insulin-mimetics",
    "insulins",
    "landogrozumab",
    "letrozole",
    "meldonium",
    "metabolic modulators",
    "myostatin",
    "myostatin inhibitors",
    "myostatin-binding proteins",
    "myostatin-neutralizing antibodies",
    "peroxisome proliferator activated receptor δ (pparδ) agonists",
    "propeptide",
    "raloxifene",
    "selective estrogen receptor modulators (serms)",
    "sr9009",
    "stamulumab",
    "tamoxifen",
    "testolactone",
    "toremifene",
    "trimetazidine")
usethis::use_data(s4_substances, overwrite = TRUE)
