## code to prepare `s5_substances` dataset goes here
s5_substances <-
  c("acetazolamide",
    "acetazolamide",
    "albumin",
    "amiloride",
    "bendroflumethiazide",
    "bumetanide",
    "canrenone",
    "canrenone",
    "canrenone",
    "canrenone",
    "chlorothiazide",
    "chlortalidone",
    "chlorthalidone",
    "desmopressin",
    "dextran",
    "etacrynic acid",
    "finasteride",
    "furosemide",
    "furosemide",
    "glycerol",
    "hydrochlorothiazide",
    "hydrochlorothiazide",
    "hydroxyethyl starch",
    "indapamide",
    "intravenous administration of albumin",
    "intravenous administration of dextran",
    "intravenous administration of hydroxyethyl starch",
    "intravenous administration of mannitol",
    "mannitol",
    "metolazone",
    "plasma expanders",
    "probenecid",
    "spironolactone",
    "spironolactone",
    "thiazides",
    "tolvaptan",
    "torsemide",
    "triamterene",
    "vaptans")
usethis::use_data(s5_substances, overwrite = TRUE)
