## code to prepare `s6_substances` dataset goes here
s6_substances <- c("1,3-dimethylbutylamine",
  "3-methylhexan-2-amine (1,2-dimethylpentylamine)",
  "4-methylhexan-2-amine (methylhexaneamine)",
  "4-methylpentan-2-amine (1,3-dimethylbutylamine)",
  "4-phenylpiracetam (carphedon)",
  "5-methylhexan-2-amine (1,4-dimethylpentylamine)",
  "adderall",
  "adrafinil",
  "adrenaline",
  "amfepramone",
  "amfetamine",
  "amfetaminil",
  "amiphenazole",
  "amphetamine",
  "benfluorex",
  "benzfetamine",
  "benzoylecgonine",
  "benzylpiperazine",
  "bromantan",
  "carphedon",
  "cathine",
  "cathinone",
  "clobenzorex",
  "cocaine",
  "cocaine",
  "cropropamide",
  "crotetamide",
  "dimetamfetamine",
  "dimethylbutylamine (dmba)",
  "dimethylpentylamine",
  "dimethylbutylamine",
  "1,4‐dimethylpentylamine",
  "1,4‐dimethylpentylamine (1,4‐dmpa)",
  "1,4‐dmpa",
  "ephedrine",
  "efedrine",# misspelling
  "epinephrine (adrenaline)",
  "etamivan",
  "etilamfetamine",
  "etilefrine",
  "famprofazone",
  "fenbutrazate",
  "fencamfamin",
  "fencamine",
  "fenetylline",
  "fenfluramine",
  "fenproporex",
  "fonturacetam 4-phenylpiracetam (carphedon)",
  "furfenorex",
  "heptaminol",
  "hydroxyamfetamine (parahydroxyamphetamine)",
  "isometheptene",
  "levmetamfetamine",
  "lisdexamfetamine",
  "meclofenoxate",
  "mefenorex",
  "mephedrone",
  "mephentermine",
  "mesocarb",
  "metamfetamine(d-)",
  "methedrone",
  "methylenedioxymethamphetamine",
  "methylephedrine",
  "methylhexaneamine",
  "methylphenidate",
  "methylhexanamine",
  "methylphenidate",
  "methylsynephrine",
  "5-methylhexan-2-amine",
  "modafinil",
  "modafinil",
  "nikethamide",
  "non-specified stimulants",
  "norfenefrine",
  "norfenfluramine",
  "octopamine",
  "oxilofrine",
  "oxilofrine (methylsynephrine)",
  "p-methylamfetamine",
  "parahydroxyamphetamine",
  "pemoline",
  "pentetrazol",
  "phendimetrazine",
  "phenethylamine",
  "phenmetrazine",
  "phenpromethamine",
  "phentermine",
  "phentermine",
  "prenylamine",
  "prolintane",
  "propylhexedrine",
  "pseudoephedrine",
  "pseudoephdrine", #include misspelling!
  "pseudoephedrine",
  "α - pyrrolidinovalerophenone",
  "strychnine",
  "tuaminoheptane")
usethis::use_data(s6_substances, overwrite = TRUE)
